### ISSUE TITLE
API Down 

### ISSUE THREAD

**Issue by SrikanthKumarC** [hemanth-kotagiri/jntuh-results#10]
# Error from frontend

The frontend is trying to fetch from https://results-restapi.herokuapp.com/ which seems to be down. 
<img width="1440" alt="Screenshot 2022-10-23 at 9 52 06 AM" src="https://user-images.githubusercontent.com/66662854/197373633-c3072d43-4870-46da-b870-93e7d0a50415.png">

# Endpoint error
<img width="1440" alt="Screenshot 2022-10-23 at 9 55 46 AM" src="https://user-images.githubusercontent.com/66662854/197373707-04a66240-01d7-4c77-8eab-02460023dd96.png">

Hope this will be fixed.

**Comment by hemanth-kotagiri** [comment]
Hey there @SrikanthKumarC . As you might be aware that JNTUH released new results yesterday(22-10-2022), and their servers are flooded with requests - which is why, our backend is facing issues with fetching the details/results from the same. The backend that we created directly leverages JNTUH servers with an assumption that they work all the time(which is not the case as you see now) which is why this issue is prevailing.

As of now, we really do not have any fix for this yet, but we soon plan to implement possible solutions in our backend.

You can expect the our application to work as soon as the servers at JNTUH ease down with their traffic a bit.
Thanks for your time, and many thanks for using our services!

**Comment by SrikanthKumarC** [comment]
Hey @hemanth-kotagiri, I checked the backend only after posting this issue; it seems you are scraping from the actual result page, which is why the error (due to high traffic).

I should have checked the backend before posting this issue. Anyways a friendly app 👏 .

I hope that JNTU moves to AWS/Azure/GCP one day.

The UI is friendly. I want to contribute to the project in my free time.

**Comment by hemanth-kotagiri** [comment]
@SrikanthKumarC Yes, the results are scraped first and serialized into JSON. 

And, JNTU moving to those platforms is quite debatable considering the fact that they've been providing results in the same way with their deteriorated servers for close to a decade now! Nor do they have load balancers, nor will they move to a better performant server(s).

Thanks for your comments on the UI, sure, you can contribute to the project anytime! We look forward to that!

You can pick up any upcoming issues over at the organization I created here: https://github.com/jntuh-results-services 

Happy Hacking!
